version: '3'
services:
  app:
    build: ./
    volumes: 
      - ./:/var/www/html
    ports:
      - 8000:8000
    environment: 
      - HOST=0.0.0.0
    container_name: app
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html